name: start_hdb_dashboard

on:
  schedule:
    - cron: "30 2 * * *"
jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo content
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies 
        run: pip installs -r requirements.txt
      - name: Create HDB Dashboards
        env:
          google_auth: ${{ secrets.GSHEET_CRED }}
          api_email: ${{ secrets.GSHEET_API_EMAIL }}
        run: python create_hdb_dash.py