name: start_hdb_dashboard

on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"
jobs:
  run-hdb_dash:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo content
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies 
        run: pip install -r requirements.txt
      - name: Create HDB Dashboards
        run: python create_hdb_dash.py
        env: MONGO_PASSWORD: ${{ secret.MONGO_PASSWORD }}
      - name: Check for changes
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m 'updated HDB dashboard'
          git push
